CREATE DATABASE tic_tac_toe;

USE tic_tac_toe;

CREATE TABLE games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  result VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50),
  password VARCHAR(255)
);